apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: docker.io/popelolole/search-service:latest
          env:
            - name: DATABASE_URL
              value: jdbc:mysql://mysql-service:3306/journaldb

            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: username

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: search-service-client-secret
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31001
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: search-service-internal
spec:
  selector:
    app: search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
