name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Package with maven
      run: mvn package
    - name: Run unit tests
      run: mvn test
  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: registry.cloud.cbh.kth.se
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      if: success()
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKER_TAG }}
        file: ./src/main/docker/Dockerfile.jvm
